<template>
    <section>
        <article class="article-page container-768">
            <h2 class="article-title mb-3">Terms of Use</h2>
            <h5 class="article-subtitle">Updated 4/15/2019</h5>

            <p><strong>PLEASE READ THESE TERMS OF SERVICE CAREFULLY.</strong></p>

            <p>You agree that by clicking “I Have Read and agree to The Capt App terms of service”, participating in the Referral Program (defined below), registering, accessing, or using our Services (described below), you are agreeing to enter into a legally binding contract with The Capt App, LLC. operating as d/b/a The Capt App, (hereafter referred to as “The Capt App”, “we”, “us”, or “our”).  If you do not agree that these Terms of Service (“Terms”) form a contract with you, or should you not wish to agree to these Terms, do not click “I have read and agree to The Capt App Terms of Service” and do not access or otherwise use any of the Services. If you do not agree to these Terms, you have no right to obtain information from or otherwise continue using the Services. Failure to use the Services in accordance with these Terms may subject you to civil and / or criminal penalties</p>

            <p>You agree to comply with and be legally bound by these Terms, whether or not you become a registered user of the Services. These Terms govern your access to and use of the Services and all Collective Content (defined below), and your participation in the Referral Program (defined below).  These Terms constitute a binding legal agreement between you and The Capt App.</p>

            <p>The Capt App provides an online platform that connects Owners who have Boats (as defined below) to Licensed Captains, accessible at http://www.TheCaptApp.com and any other websites through which The Capt App makes the platform available (collectively, the “Site") with any other websites, applications, features, software or services provided, owned, or operated by The Capt App that link to these Terms are, collectively, the “Services”.</p>

            <p>Your use of our Services is also subject to our Privacy Policy. Other services offered by The Capt App may be subject to separate terms.</p>

            <p>YOU UNDERSTAND AND AGREE THAT The Capt App IS NOT A PARTY TO ANY AGREEMENTS ENTERED INTO BETWEEN OWNERS AND CAPTAINS, NOR IS The Capt App A BOAT BROKER, AGENT OR INSURER. The Capt App HAS NO CONTROL OVER THE CONDUCT OF OWNERS, CAPTAINS AND OTHER USERS OF THE SITE, APPLICATION AND SERVICES OR ANY BOATS, AND DISCLAIMS ALL LIABILITY IN THIS REGARD.</p>


            <p>When using or opening an account with The Capt App on behalf of a company, entity, or organization, you represent and warrant that you: (i) are an authorized representative of that entity with the authority to bind that organization to these Terms and grant the licenses set forth; and (ii) agree to these Terms on behalf of such entity.</p>

            <p><strong>Definitions</strong></p>
            <p>Owners are  responsible for all aspects of the Boat during the trip including manning, vetting, proper safety equipment, provisioning and otherwise.</p>
            <p>“Boat(s)” means marine vessels.</p>
            <p>“The Capt App Content” means all Content that The Capt App makes available through the Services, including any Content licensed from a third party, but excluding Member Content.</p>
            <p>“Collective Content” means Member Content and The Capt App Content.</p>
            <p>“Content” means text, graphics, images, music, software, audio, video, information and any other content or materials.</p>
            <p>“Captain” means a U.S.C.G. Licensed Captain who agrees to operating of a Boat at the Owners request.</p>
            <p>“Fee” means the percentage charged to the Captain for using this service.</p>
            <p>“Owner” means a person who requests a Captain to operate their vessel, is responsible for vetting Captains, Ensuring the vessel has proper insurance, ensuring the vessel has proper tow coverage. The Owner does not have to be the boat Boat Owner, but will need to be appointed and approved by the Boat Owner.</p>
            <p>“Member” means a person who completes The Capt App's account registration process, including, but not limited to Owners and Captains</p>
            <p>“Member Content” means all Content that a Member posts, uploads, publishes, submits or transmits to be made available through the Services.</p>
            <p>“Time Charter” A rental of a Boat supported by a written agreement whereby the Boat Owner makes the Boat available to the Renter but the Owner remains responsible for all aspects of operating the Boat including but not limited to manning and provisioning the Boat. An Owner of a Boat rented pursuant to a Time Charter must ensure compliance with all applicable coast guard, local, state and federal laws for the specific type of operation of the Boat.</p>
            <p>“Tax” or “Taxes” mean any sales taxes, goods and services taxes (GST), value added tax (VAT), and any other applicable or similar municipal, state and federal indirect or other withholding and personal or corporate income taxes. Certain areas of the Services (and your access to or use of certain aspects of the Services or Collective Content) may have different terms and conditions posted or may require you to agree with and accept additional terms and conditions. If there is a conflict between these Terms and the terms and conditions posted for a specific area of the Services, the latter terms and conditions will take precedence with respect to your use of or access to that area of the Services.</p>

            <p><strong>Modification</strong></p>
            <p>The Capt App reserves the right, at its sole discretion, to modify the Services or to modify these Terms, including the Fees (defined below), at any time and without prior notice. If we modify these Terms, we will post the modification on the Services or provide you with notice of the modification. We will also update the “Last Updated Date” at the top of these Terms. Your continued use of our Services after we publish or send a notice about our changes to these Terms means that you are consenting to the updated Terms. If the modified Terms are not acceptable to you, your only recourse is to cease using the Services.</p>
            <p><strong>Other Policies</strong></p>
            <p>You agree that you will comply with all written The Capt App rules, agreements, and policies that are made available in these terms.</p>
            <p><strong>Minimum Age</strong></p>
            <p>The Services are intended solely for persons who are 18 or older. Any access to or use of the Services by anyone under 18 is expressly prohibited. By accessing or using the Services you represent and warrant that you are 18 or older.</p>
            <p><strong>How the Services Work</strong></p>
            <p>The Services can be used to facilitate Owners who are searching for a Captain. You may view Captains near you once you register as an Owner. Captains who wish to list their services must first register to create a The Capt App Account (defined below). As stated above, The Capt App makes available a platform or marketplace with related technology for Captains and Owners to meet online and arrange for bookings of Captains. The Capt App is not an Owner or operator of Boats, including, but not limited to, powerboats, sailboats, ski boats, yachts, houseboats, kayaks, or other Boats, nor is it a provider of Boats, including, but not limited to, powerboats, sailboats, ski-boats, yachts, houseboats, kayaks, or other Boats, and The Capt App does not own, sell, resell, furnish, provide, rent, re-rent, manage and/or control Boats, including, but not limited to, powerboats, sailboats, ski boats, yachts, houseboats, kayaks, or other Boats, or transportation or travel services. The Captain App does not license or qualify the Captains abilities to navigate/operate a vessel. The Capt App’s responsibilities are limited to: (i) facilitating the availability of the Services and (ii) serving as the limited agent of each Captain for the sole purpose of accepting payments from Owner on behalf of the Captain.</p>
            <p>PLEASE NOTE THAT, AS STATED ABOVE, THE SERVICES ARE INTENDED TO BE USED TO FACILITATE THE BOOKING OF CAPTAINS. The Capt App CANNOT AND DOES NOT CONTROL THE CONTENT CONTAINED IN ANY OF THE CAPTAINS LISTINGS AND/OR THE CONDITION, LEGALITY OR SUITABILITY OF ANY BOATS. The Capt App IS NOT RESPONSIBLE FOR AND DISCLAIMS ANY AND ALL LIABILITY RELATED TO ANY AND ALL BOOKINGS AND BOATS. ACCORDINGLY, ANY BOOKINGS WILL BE MADE AT THE CAPTAINS AND OWNER’S OWN RISK.</p>
            <p><strong>Account Registration</strong></p>
            <p>In order to access certain features of the Services, and to book a Captain or create a Listing, you must register to create an account (“The Capt App Account”) and become a Member. You may register to join the Services directly via the Services or as described in this section.</p>
            <p>The Capt App makes no effort to review any TPA Content for any purpose, including but not limited to, for accuracy, legality or non-infringement and The Capt App is not responsible for any TPA Content.</p>

            <p>You may not have more than one (1) active The Capt App Account. You agree to provide accurate, current and complete information during the registration process and to update such information to keep it accurate, current and complete. The Capt App reserves the right to suspend or terminate your The Capt App Account and your access to the Services if you create more than one (1) The Capt App Account or if any information provided during the registration process or thereafter proves to be inaccurate, not current or incomplete.</

            <p>You are responsible for safeguarding your password. You agree that you will not disclose your password to any third party and that you will take sole responsibility for any activities or actions under your The Capt App Account, whether or not you have authorized such activities or actions. You will immediately notify The Capt App of any unauthorized use of your The Capt App Account.</p>

            <p>Unless expressly permitted in writing by The Capt App, you may not sell, rent, or lease your The Capt App Account to anyone else.</p>

            <p><strong>Captain Services</strong></p>
            <p>As a Member, you may create a profile. You will be asked a variety of questions about yourself, including, but not limited to, License class, experience, referrals, your agreement to a background check, availability,  pricing, and related rules. You acknowledge and agree that your profile will be made publicly available via the Services. Other Members will be able to contact you via the Services based upon the information provided in your Profile. You understand and agree that once a Owner requests a booking of your Services , the price for such booking may not be altered without contacting customer service (contact@TheCaptApp.com).</p>

            <p>You acknowledge and agree that you are responsible for any and all details of the Profile you post. Accordingly, you represent and warrant that any Profile you post and the booking of, (i) will not breach any agreements you have entered into with any third parties and (ii) will (a) be in compliance with all applicable laws, tax requirements, and rules and regulations that may apply, including, but not limited to, insurance requirements, coast guard regulations, zoning laws, marina regulations, and laws governing rentals and operation of Boats and (b) not conflict with the rights of third parties. Please note that The Capt App assumes no responsibility for an Owner’s compliance with any applicable laws, rules and regulations. The Capt App reserves the right, at any time and without prior notice, but without obligation to do so, to remove or disable access to any Profile for any reason, including Profiles that The Capt App, in its sole discretion, considers to be objectionable for any reason, in violation of these Terms or otherwise harmful to the Services.</p>

            <p>You understand and agree that The Capt App does not act as an insurer or as a contracting agent for you as an Captain. If a Owner requests a booking of your Services and you operate their Boat, any agreement you enter into with such Owner is between you and the Owner and The Capt App is not a party thereto. Notwithstanding the foregoing, The Capt App serves as the limited authorized payment agent of the Captain for the sole purpose of accepting payments from Owner on behalf of the Captain and is responsible for transmitting such payments with applicable fees to the Captain.</p>

            <p>When you create a Profile, you may also choose to include certain requirements which must be met by the Members who are eligible to request a booking of your Services, including, but not limited to, requiring Members to have a profile picture or verified phone number, in order to book your Services. Any Member wishing to book or offer Services with such requirements must meet these requirements; however, as noted below, we do not attempt to confirm or verify such information.</p>

            <p>If you are an Owner, The Capt App makes certain tools available to you to help you to make informed decisions about which Members you choose to confirm for booking your Boat. You acknowledge and agree that, as an Owner, you are responsible for your own acts and omissions.</p>

            <p><strong>No Endorsement</strong></p>
            <p>The Capt App does not endorse any Members, Owners or Captains. Although these Terms require Members to provide accurate information, we do not attempt to confirm, and do not confirm, any Member’s purported identity or other information provided by such Member. You are responsible for determining the identity and suitability of others who you contact via the Services. Except as provided by the The Capt App Terms, we will not be responsible for any damage or harm resulting from your interactions with other Members.</p>
            <p>By using the Services, you agree that any legal remedy or liability that you seek to obtain for actions or omissions of other Members or other third parties will be limited to a claim against the particular Members or other third parties who caused you harm and you agree not to attempt to impose liability on, or seek any legal remedy from The Capt App with respect to such actions or omissions. Accordingly, we encourage you to communicate directly with other Members on the Services regarding any bookings made by you. This limitation shall not apply to any claim by a Captain against The Capt App regarding the remittance of payments received from an Owner by The Capt App on behalf of an Owner, which instead shall be subject to the limitations described in the section below entitled “Limitation of Liability”.</p>
            <p><strong>Bookings and Financial Terms</strong></p>
            <p>If you are an Captain and a booking is requested for your Services, you may be required to either confirm or reject the booking within 24 hours of when the booking is requested (as determined by The Capt App in its sole discretion) or the booking request may be automatically canceled. When a booking is requested via the Services, we will share with you (i) the first and last name of the Owner who has requested the booking, and, (ii) a link to the Owner’s The Capt App Account profile page, so that you can view such information before confirming or rejecting the booking. When you confirm a booking requested by an Owner, The Capt App will send you an email, text message or message via the Services confirming such booking, depending on the selections you make via the Services.</p>
            <p>The fees displayed in each Booking are comprised of the Captains Fees and the Operating Fees. Where applicable, Taxes may be charged in addition to the Reservation Fees and Boat Fees. The Captains Fees, the Operating Fees and applicable Taxes are collectively referred to in these Terms as the “Total Fees”. The amounts due and payable by an Owner solely relating to the Captains Services  which are actually collected by The Capt App are the Operating Fees. Please note that it is the Captain, and not The Capt App which determines the Boat Fees. The Captain Fees may include cleaning fees and / orany other custom trip request, at the Captain's discretion which should be higlighted before the trip is confirmed.</p>
            <p>The Owner is liable for the following expenses including  but not limited to all fuel expenses, vessel operating expenses during the trip and any other vessel related expense.</p>
            <p>The Captains may bill the owner for the following expenses including but not limited to, transportation, meals, hotels and any other trip relalted expense.</p>
             <p>The Capt App charges a fee to Owners based upon the Captains original quote; this charge is referred to as the “Booking Fees”.</p>
             <p>The Capt App will collect the Total Fees at the time of booking confirmation (i.e. when the Owner confirms the Captains booking within 24 hours of the booking request) and will initiate payment of the Booking Fees (less The Capt App’s Service Fees as defined in the Fees Policy shown to the Captain at the time of trip quotation) to the Captain two business days after the completion of the trip provided The Capt App has the accurate account information (except to the extent that a refund is due to the Owner).</p>
            <p>Failure to charge any of the fees or other indulgences shall not constitute a waiver of the right to exercise the same in the event another fee should become due at any other time.</p>
            <p>You also agree that if The Capt App is unable to collect a debt that is due within 30 (thirty) days, it may resort to a third party recovery service for the amount owed. In the event a third party recovery service is used, you agree that The Capt App may pursue an action against you for the original amount owed, plus any commissions or expenses (including attorneys’ fees) related to pursuing said amount.</p>
            <p><strong>Agreed Exclusivity with The Capt App</strong></p>
            <p>As an Captain, you agree to use the Service to communicate and facilitate a booking with an Owner. You agree not to take any action directly or indirectly to circumvent the Service Fee Policy. If you do so, you agree that The Capt App may charge you a fee up to $1,000 per booking, in addition to the Service Fees otherwise owed to The Capt App.  The Capt App may collect the fee from future bookings or otherwise.</p>

            <p><strong>Insurance</strong></p>
            <p>It is the Owners responsibility to  review the insurance for their vessel. Please review any insurance policy carefully, and in particular please make sure that you are familiar with and understand any exclusions to, and any deductibles that may apply for, such insurance policy, including, but not limited to, whether or not your insurance policy will cover the actions or inactions of, or relating to any hired Captains while on the Boat. Owners acknowledge that they are giving the Captain they chose to hire or book permission to operate their vessel during the trip.</p>
            <p><strong>Appointment of The Capt App as Limited Payment Agent for Captain</strong></p>
            <p>Each Captain hereby appoints The Capt App as the Owner's limited agent solely for the purpose of collecting payments made by Owner on behalf of the Captain. Each Captain agrees that payment of Booking Fees made by a Renter to The Capt App shall be considered the same as a payment made directly to the Captain and the Captain will make the themselves available to Owner in the agreed upon manner as if the Captain has received the Booking Fees. Each Captain agrees that The Capt App may, in accordance with the cancellation policy selected by the Owner and reflected in the relevant Listing, (i) permit the Owner to cancel the booking and (ii) refund to the Owner that portion of the Booking Fees specified in the applicable cancellation policy. In accepting appointment as the limited authorized payment agent of the Captain, The Capt App assumes no liability for any acts or omissions of the Captain.</p>
            <p>From time to time, we may become aware of users attempting to conduct a transaction that would involve an unauthorized payment method or a fraudulent payment method.  Ideally, we hope to be able to assist users in avoiding such transactions, but we assume no liability or responsibility to either do so or to inform users of any such actual or suspected activity.</p>
            <p>You are immediately responsible to The Capt App for all credit card disputes, refunds, reversals, or fines regardless of the reason or timing. In many but not all cases, you may have the ability to challenge such actions by submitting evidence to contact@TheCaptApp.com. We may request additional information to provide to Financial Services Providers to assist you in contesting the charge, but we cannot guarantee that your challenge will be successful. Financial Services Providers may deny your challenge for any reason they deem appropriate. Where a challenge is entirely or partially successful, a Financial Services Provider may credit funds associated with the charge that is the subject of the dispute (or a portion thereof).</p>

            <p>Please keep in mind that you are liable for all losses you incur when lost or stolen payment credentials or accounts are used to purchase products or services from you. The Capt App does not and will not insure you against losses caused by fraud under any circumstances.</p>

            <p><strong>No Charge for Creating a Profile</strong></p>

            <p>Please note that The Capt App does not currently charge fees for the creation of a member profile. However, you acknowledge and agree that The Capt App reserves the right, in its sole discretion, to charge you for and collect fees from you for the creation of Bookings, or for other features of the Services. Please note that The Capt App will provide notice of any such additional fees via the Services, prior to implementing such fees.</p>

            <p><strong>Bookings and Financial Terms for Renters</strong></p>
            <p>The Captain, not The Capt App, are solely responsible for honoring any confirmed bookings and making themselves available for the Services that were agreed to reserved through the Services. If you, as a Owner, choose to enter into a transaction with an Captain for the booking of a their services, you agree and understand that you will be required to enter into an agreement with the Captain and you agree to accept any terms, conditions, rules and restrictions associated with such imposed by the Captain. You acknowledge and agree that you, and not The Capt App, will be responsible for performing the obligations of any such agreements, that The Capt App is not a party to such agreements, and that, with the exception of its obligations hereunder to pay Boat Fees to the applicable Owner, The Capt App disclaims all liability arising from or related to any such agreements. You acknowledge and agree that, notwithstanding the fact that The Capt App is not a party to the agreement between the Captain and the Owner, The Capt App acts as the Captain’s limited payment agent for the limited purpose of accepting payments from you on behalf of the Owner. Upon your payment of amounts to The Capt App which are due to the Captain, your payment obligation to the Captain for such amounts is extinguished, and The Capt App is responsible for remitting such amounts, less The Capt App’s Booking Fees, to the Owner. In the event that The Capt App does not remit any such amounts to a Captain, such Captain will have recourse for such amounts only against The Capt App.</p>

            <p>The Owner agree to pay The Capt App for the Total Fees for any booking requested in connection with your The Capt App Account if such requested bookings are confirmed by the applicable Captain. In order to establish a booking pending the applicable Owner’s confirmation of your requested booking, you understand and agree that The Capt App, on behalf of the Captain, reserves the right, in its sole discretion, to (i) obtain a pre-authorization via your credit card for the Total Fees or (ii) charge your credit card a nominal amount, not to exceed one dollar ($1) to verify your credit card. Once The Capt App receives confirmation of your booking from the applicable Owner, The Capt App will collect the Total Fees in accordance with these Terms and the pricing terms set forth in the applicable Listing. Please note that The Capt App cannot control any fees that may be charged to a Owner by his or her bank related to The Capt App's collection of the Total Fees, and The Capt App disclaims all liability in this regard.</p>

            <p>In connection with your requested booking, you will be asked to provide billing information such as name, billing address and credit card information either to The Capt App or its third party payment processor. You agree to pay The Capt App for any confirmed bookings made in connection with your The Capt App Account in accordance with these Terms by one of the methods described on the Service – e.g. by PayPal or credit card. You hereby authorize the collection of such amounts by charging the credit card provided as part of requesting the booking, either directly by The Capt App or indirectly, via a third party online payment processor or by one of the payment methods described on the Services. </p>

            <p><strong>Payment Processing Errors and Chargebacks</strong></p>
            <p>We will take steps to rectify any payment processing errors that we become aware of. These steps may include crediting or debiting (as appropriate) the same payment method used for the original payout to or payment by you, so that you end up receiving or paying the correct amount.</p>

            <p>If an Captain is paid for a trip erroneously or a chargeback takes place, The Capt App will first attempt to debit the funds from the provided bank account.  If The Capt App is unable to debit the funds to the Owner, the Captain is responsible for returning those funds within seven (7) days. The Capt App may collect all future payouts until the erroneous payment or chargebacks have been resolved.</p>

            <p><strong>Payment Processor Terms (Stripe)</strong></p>
            <p>Payment processing services on The Capt App are provided by Stripe and are subject to the Stripe Connected Account Agreement, which includes the Stripe Terms of Service(collectively, the “Stripe Services Agreement”). You agree to be bound by the Stripe Services Agreement. You also authorize The Capt App to share with Stripe transaction information related to your use of the payment processing services provided by Stripe.</p>

            <p><strong>Booking Fees</strong></p>
            <p>In consideration for providing the Services, The Capt App collects service fees from Captains. Booking Fees are made up of one (1) components: (i) a Commission Fee that is charged to the Captain, each is based upon a percentage of the amount of the Booking Fees. Where applicable, Taxes may also be charged. The Capt App Commission Fees are deducted from the Booking Fees before remitting the Captains Fees to the Captain. </p>
            <p>The agreed upon Captain payout amount will be remitted by The Capt App to Captain via direct deposit or other payment methods described on the Services, in U.S. dollars.. Except as otherwise provided herein, Service Fees are non-refundable.</p>

            <p><strong>Captains</strong></p>
            <p>Bareboat Rentals:  Where a Renter elects to hire a captain to meet the minimum manning requirements for a Boat during a Bareboat Rental the following applies:</p>
            <p>Owner is free to select any captain who  meets the minimum manning qualifications established by the Owner for the rental Boat Captain Service Agreement. The hiring of a captain by a Renter is subject to the terms and conditions of the Boat Captain Service Agreement between the Owner and the Owners chosen captain.</p>

            <p>No Endorsement. In order to promote safety and a great experience The Capt App may provide a list of available captains whom may be available to be hired by the Owner where requested by the Owner. The Capt App CANNOT AND DOES NOT CONTROL THE CONTENT CONTAINED IN ANY LISTINGS OR OFFERINGS BY CAPTAINS NOR THE CONDITION, LEGALITY, SUITABILITY, INSURABILITY OR QUALIFICATIONS OF ANY CAPTAINS. The Capt App never approves or endorses any captain. The Capt App requires captains to submit evidence of their qualifications at the time of initial sign up but does not and is not responsible to ensure that a captain’s credentials remain current at the time of any particular Booking. Ensuring that a captain is currently credentialed and properly qualified for a particular Booking is the sole responsibility of the Owner</p>

            <p>Captains Are Strictly Retained by Owner. Owner agrees that it alone will be the employer of any captain selected and / or hired by Renter and that said captain will be so notified by Owner and agree that they are not the employee or borrowed servant of The Capt App and will make no claims of any kind against Owner or The Capt App on the basis of any alleged employment relationship.</p>

            <p>Owner is solely responsible for obtaining / confirming the proper insurance coverage for any paid operator /Captain hired by the Owner.</p>

            <p>Captain’s Fee. Captains are responsible to set the net amount they wish to charge for their Services. Owners are responsible for payment of the captain’s fee.  In the event of a Booking being canceled by Owner the policy as set forth in the Boat Captain Service Agreement will control.</p>

            <p><strong>General Booking and Financial Terms</strong></p>
            <p><em>Damage to Boats</em><br />
            As a Owner , you are responsible for the condition of the vessel, fair wear and tear excepted. You acknowledge and agree that, as a Owner, you are responsible for your own acts and omissions and are also responsible for the acts and omissions of any individuals who you invite to, or otherwise provide access to the Boat.</p>
            <p>Both Captains and Boat Owner agree to cooperate with and assist The Capt App in good faith, and to provide The Capt App with such information and take such actions as may be reasonably requested by The Capt App, in connection with any complaints or claims made by Members relating to Boats or any personal or other property located at a Boat or with respect to any investigation undertaken by The Capt App or a representative of The Capt App regarding use or abuse of the Site, Application or the Services.</p>

            <p><strong>Cancellations and Refunds</strong></p>
            <p>If, as a Owner, you cancel your requested booking before the requested booking is confirmed by an Captaing, The Capt App will cancel any pre-authorization to your credit card and/or refund any nominal amounts charged to your credit card in connection with the requested booking within a commercially reasonable time. If, as a Owner or Captain, you wish to cancel a confirmed booking made via the Services, either prior to or after arriving at the Boat, the cancellation policy of the applicable Listing will apply to such cancellation. Our ability to refund the Booking Fees and other amounts charged to you will depend upon the terms of the applicable cancellation policy. Details regarding refunds and cancellation policies are available via the Services.</p>
            <p><strong>Taxes</strong></p>
            <p>IRS regulation, regarding federal tax reporting requirements, stipulates that The Capt App must collect IRS Form W-9 from all Captains in the United States. You understand and agree that you are solely responsible for determining your applicable Tax reporting requirements in consultation with your tax advisors. The Capt App cannot and does not offer Tax-related advice to any Members of the Site, Application and Services. Additionally, please note that each Captain is responsible for determining local indirect Taxes and for including any applicable Taxes to be collected or obligations relating to applicable Taxes in Listings..
            Depending on your account status, forms submitted to The Capt App, and other factors, you may receive a Tax form from The Capt App.  As always, we encourage you to consult a tax professional for assistance reporting your income. The Capt App expects to issue Tax forms as follows:</p>

            <p>1099 K Requirements - The Internal Revenue Service (IRS) requires that all US companies operating as a third party settlement organization (TPSO) report any information concerning third network transactions of any participating payee only if, for the calendar year:</p>
            <p>The gross amount of total reportable payment transactions exceeds $20,000, AND The total number of such transactions exceeds 200.</p>
            <p>If a business makes payments via a third party settlement organization as well as cash or check to the same independent contractor, the TPSO will be required to report the amount of reportable transactions that exceed the de minimis thresholds on Form 1099-K.  If you cross both IRS thresholds in a calendar year, The Capt App will provide you with a Form 1099-K.</p>
            <p>Keep in mind that The Capt App cannot and does not offer tax-related advice to any members on the site. Additionally, please note that each Captain is responsible for determining local indirect taxes and for including any applicable taxes to be collected or obligations relating to applicable taxes in listings. You can read more on taxes by clicking on the link to the IRS page that better explains the Sharing Economy Tax.</p>

            <p><strong>User Conduct</strong></p>
            <p>You understand and agree that you are solely responsible for compliance with any and all laws, rules, regulations, and Tax obligations that may apply to your use of the Services and Content. In connection with your use of our Services, you may not and you agree that you will not:</p>
            <p>violate any local, state, provincial, national, maritime or other law or regulation, or any order of a court, including, without limitation, zoning restrictions, admiralty law and Tax regulations;</p>

            <p>use manual or automated software, devices, scripts, robots, other means or processes to access, scrape, crawl or spider any web pages or other services contained in the Services or Content;</p>

            <p>use the Services for any commercial or other purposes that are not expressly permitted by these Terms;</p>

            <p>Falsely imply that The Capt App endorses you, is a partner, or otherwise misleads others as to your affiliation with The Capt App;</p>

            <p>copy, store or otherwise access any information contained on the Services or Content for purposes not expressly permitted by these Terms;</p>

            <p>Use boat ramps where you have not been authorized to operate.</p>

            <p>infringe the rights of any person or entity, including without limitation, their intellectual property, privacy, publicity or contractual rights;</p>

            <p>interfere with or damage our Services, including, without limitation, through the use of viruses, cancel bots, Trojan horses, harmful code, flood pings, denial-of-service attacks, packet or IP spoofing, forged routing or electronic mail address information or similar methods or technology;</p>

            <p>use our Services to transmit, distribute, post or submit any information concerning any other person or entity, including without limitation, photographs of others without their permission, personal contact information or credit, debit, calling card or account numbers;</p>

            <p>use our Services in connection with the distribution of unsolicited commercial email (“spam”) or advertisements unrelated to the rental of boats;</p>

            <p>stalk or harass any other user of our Services or collect or store any personally identifiable information about any other user other than for purposes of transacting as a The Capt App Captain or Owner;</p>

            <p>register for more than one The Capt App Account or register for a The Capt App Account on behalf of an individual other than yourself;</p>

            <p>contact an Owner for any purpose other than asking a question related to their booking</p>

            <p>contact a Captain for any purpose other than asking a question related to their Services;</p>

            <p>when acting as a Captain or otherwise, recruit or otherwise solicit any Owner or other Member to join third party services or websites that are competitive to The Capt App, without The Capt App’s prior written approval;</p>

            <p>impersonate any person or entity, or falsify or otherwise misrepresent yourself or your affiliation with any person or entity;</p>

            <p>use automated scripts to collect information or otherwise interact with the Services;</p>

            <p>use the Services to find an Owner or Captain and then complete a booking of a Boat transaction independent of the Services in order to circumvent the obligation to pay any Booking Fees related to The Capt App’s provision of the Services;</p>

            <p>as an Captain, submit any quotation with a false or misleading price information, or submit any quotationwith a price that you do not intend to honor;</p>

            <p>post, upload, publish, submit or transmit any Content that, in The Capt App’s sole judgment: (i) infringes, misappropriates or violates a third party's patent, copyright, trademark, trade secret, moral rights or other intellectual property rights, or rights of publicity or privacy; (ii) violates, or encourages any conduct that would violate, any applicable law or regulation or would give rise to civil or criminal liability; (iii) is fraudulent, false, misleading or deceptive; (iv) is defamatory, obscene, pornographic, vulgar or offensive; (v) promotes discrimination, bigotry, racism, hatred, harassment or harm against any individual or group; (vi) is violent or threatening or promotes violence or actions that are threatening to any other person; or (vii) promotes illegal or harmful activities or substances;</p>

            <p>systematically retrieve data or other content from our Services to create or compile, directly or indirectly, in single or multiple downloads, a collection, compilation, database, directory or the like, whether by manual methods, through the use of bots, crawlers, or spiders, or otherwise;</p>

            <p>use, display, mirror or frame the Services, or any individual element within the Services, The Capt App’s name, any The Capt App trademark, logo or other proprietary information, or the layout and design of any page or form contained on a page, without The Capt App’s express written consent;</p>

            <p>access, tamper with, or use non-public areas of the Services, The Capt App’s computer systems, or the technical delivery systems of The Capt App’s providers;</p>

            <p>attempt to probe, scan, or test the vulnerability of any The Capt App system or network or breach any security or authentication measures;</p>

            <p>avoid, bypass, remove, deactivate, impair, descramble, or otherwise circumvent any technological measure implemented by The Capt App or any of The Capt App’s providers or any other third party (including another user) to protect the Services or Collective Content;</p>

            <p>forge any TCP/IP packet header or any part of the header information in any email or newsgroup posting, or in any way use the Services or Collective Content to send altered, deceptive or false source-identifying information;</p>

            <p>attempt to decipher, decompile, disassemble or reverse engineer any of the software used to provide the Services or Collective Content; or</p>

            <p>advocate, encourage, or assist any third party in doing any of the foregoing.</p>

            <p>The Capt App will have the right to investigate and prosecute violations of any of the above to the fullest extent of the law. The Capt App may involve and cooperate with law enforcement authorities in prosecuting users who violate these Terms. You acknowledge that The Capt App has no obligation to monitor your access to or use of the Services or Collective Content or to review or edit any Member Content, but has the right to do so for the purpose of operating the Services, to ensure your compliance with these Terms, or to comply with applicable law or the order or requirement of a court, administrative agency or other governmental body. The Capt App reserves the right, at any time and without prior notice, to remove or disable access to any Collective Content that The Capt App, at its sole discretion, considers to be objectionable for any reason, in violation of these Terms or otherwise harmful to the Services.</p>

            <p><strong>Privacy</strong></p>
            <p>See The Capt App’s Privacy Policy at http://www.TheCaptApp.com/privacy for information and notices concerning The Capt App’s collection and use of your personal information.</p>

            <p><strong>Ownership</strong></p>
            <p>The Services are owned and operated by The Capt App. Unless otherwise indicated, all content, information, and other materials on the Services (excluding Member Content), including, without limitation, The Capt App’s trademarks and logos, the visual interfaces, graphics, design, compilation, information, software, computer code (including source code or object code), services, text, pictures, information, data, sound files, other files and the selection and arrangement thereof (collectively, the “Materials”) are protected by relevant intellectual property and proprietary rights and laws. All Materials contained on the Services are the property of The Capt App or its subsidiaries or affiliated companies and/or third-party licensors. Unless otherwise expressly stated in writing by The Capt App, by agreeing to these Terms you are granted a limited, non-sublicensable license (i.e. a personal and limited right) to access and use the Services solely for your personal use or business use as identified in these Terms.  The Capt App can terminate this license at any time, without notice.</p>

            <p>No licenses or rights are granted to you by implication or otherwise under any intellectual property rights owned or controlled by The Capt App or its licensors, except for the licenses and rights expressly granted in these Terms.</p>

            <p><strong>Member Content, License to The Capt App</strong></p>
            <p>Unless otherwise agreed to in a written agreement between you and The Capt App that was signed by an authorized representative of The Capt App, if you submit, transmit, display, perform, post or store Member Content using the Services, you grant The Capt App and its sublicensees an unrestricted, worldwide, perpetual, irrevocable, fully sub-licenseable, nonexclusive, and royalty-free right to (a) use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform and display such Member Content (including without limitation for promoting and redistributing part or all of the Services (and derivative works thereof)) in any form, format, media or media channels now known or later developed or discovered; and (b) use the name, identity, likeness and voice (or other biographical information) that you submit in connection with such Member Content.</p>

            <p><strong>Member Content Representations</strong></p>
            <p>You are solely responsible for your Member Content and the consequences of posting or publishing it. By uploading and publishing your Member Content, you represent, and warrant that: (1) you are the creator and owner of the Member Content or otherwise have sufficient rights and authority to grant the rights granted herein; (2) your Member Content does not and will not (a) infringe, violate, or misappropriate any third-party right, including any copyright, trademark, patent, trade secret, moral right, privacy right, right of publicity, or any other intellectual property or proprietary right or (b) defame any other person; and (3) your Member Content does not contain any viruses, adware, spyware, worms, or other harmful or malicious code. The Capt App reserves all rights and remedies against any Members who breach these representations and warranties.</p>

            <p><strong>Links</strong></p>
            <p>The Services may contain links to third-party websites or resources. You acknowledge and agree that The Capt App is not responsible or liable for: (i) the availability or accuracy of such websites or resources; or (ii) the content, products, or services on or available from such websites or resources. Links to such websites or resources do not imply any endorsement by The Capt App of such websites or resources or the content, products, or services available from such websites or resources. You acknowledge sole responsibility for and assume all risk arising from your use of any such websites or resources or the Content, products or services on or available from such websites or resources.</p>

            <p><strong>Proprietary Rights Notices</strong></p>
            <p>All trademarks, service marks, logos, trade names and any other proprietary designations of The Capt App used herein are trademarks or registered trademarks of The Capt App. Any other trademarks, service marks, logos, trade names and any other proprietary designations are the trademarks or registered trademarks of their respective parties.</p>
            <p><strong>Feedback</strong></p>
            <p>We welcome and encourage you to provide feedback, comments and suggestions for improvements to the Services (“Feedback”). You may submit Feedback through our website. You acknowledge and agree that all Feedback will be the sole and exclusive property of The Capt App and you assign to The Capt App all of your right, title, and interest in and to all Feedback, including without limitation all worldwide patent, copyright, trade secret, moral and other proprietary or intellectual property rights therein. At The Capt App's request and expense, you will execute documents and take such further acts as The Capt App may reasonably request to assist The Capt App to acquire, perfect, and maintain its intellectual property rights and other legal protections for the Feedback.</p>

            <p><strong>Copyright Dispute Policy</strong></p>
            <p>The Capt App respects copyright law and expects its users to do the same.  If you are a copyright owner or agent thereof and believe that content posted on the The Capt App Services infringes upon your copyright, please submit a notice following our Policy, which include further information about what to include in your notice, and where to submit your notice</p>

            <p><strong>Termination and The Capt App Account Cancellation</strong></p>
            <p>We may, in our discretion and without liability to you, with or without cause, with or without prior notice and at any time: (a) terminate these Terms or your access to our Services, and (b) deactivate or cancel your The Capt App Account. Upon termination we will promptly pay you any amounts we reasonably determine we owe you in our discretion, which we are legally obligated to pay you. In the event The Capt App terminates these Terms, or your access to our Services or deactivates or cancels your The Capt App Account you will remain liable for all amounts due hereunder. You may cancel your The Capt App Account at any time by contacting us. Please note that if your The Capt App Account is canceled, we do not have an obligation to delete or return to you any Content you have posted to the Services, including, but not limited to, any reviews or Feedback.</p>

            <p><strong>Disclaimers</strong></p>
            <p>IF YOU CHOOSE TO USE THE SERVICES, YOU DO SO AT YOUR SOLE RISK. YOU ACKNOWLEDGE AND AGREE THAT The Capt App DOES NOT HAVE AN OBLIGATION TO CONDUCT BACKGROUND CHECKS ON ANY MEMBER, INCLUDING, BUT NOT LIMITED TO, RENTERS AND OWNERS, BUT MAY CONDUCT SUCH BACKGROUND CHECKS IN ITS SOLE DISCRETION. THE SERVICES, COLLECTIVE CONTENT ARE PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED. WITHOUT LIMITING THE FOREGOING, The Capt App EXPLICITLY DISCLAIMS ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE. The Capt App MAKES NO WARRANTY THAT THE SERVICES, COLLECTIVE CONTENT, INCLUDING, BUT NOT LIMITED TO, THE LISTINGS OR ANY BOATS, WILL MEET YOUR REQUIREMENTS OR BE AVAILABLE ON AN UNINTERRUPTED, SECURE, OR ERROR-FREE BASIS. The Capt App MAKES NO WARRANTY REGARDING THE QUALITY OF ANY LISTINGS, BOATS, THE SERVICES OR COLLECTIVE CONTENT OR THE ACCURACY, TIMELINESS, TRUTHFULNESS, COMPLETENESS OR RELIABILITY OF ANY COLLECTIVE CONTENT OBTAINED THROUGH THE SERVICES.</p>

            <p>NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED FROM The Capt App OR THROUGH THE SERVICES OR COLLECTIVE CONTENT, WILL CREATE ANY WARRANTY NOT EXPRESSLY MADE HEREIN.</p>

            <p>YOU ARE SOLELY RESPONSIBLE FOR ALL OF YOUR COMMUNICATIONS AND INTERACTIONS WITH OTHER USERS OF THE SERVICES AND WITH OTHER PERSONS WITH WHOM YOU COMMUNICATE OR INTERACT AS A RESULT OF YOUR USE OF THE SERVICES, INCLUDING, BUT NOT LIMITED TO, ANY OWNERS OR RENTERS. YOU UNDERSTAND THAT The Capt App DOES NOT MAKE ANY ATTEMPT TO VERIFY THE STATEMENTS OF USERS OF THE SITE, APPLICATION OR SERVICES OR TO REVIEW OR INSPECT ANY BOATS. The Capt App MAKES NO REPRESENTATIONS OR WARRANTIES AS TO THE CONDUCT OF USERS OF THE SITE, APPLICATION OR SERVICES OR THEIR COMPATIBILITY WITH ANY CURRENT OR FUTURE USERS OF THE SITE, APPLICATION OR SERVICES. YOU AGREE TO TAKE REASONABLE PRECAUTIONS IN ALL COMMUNICATIONS AND INTERACTIONS WITH OTHER USERS OF THE SITE, APPLICATION OR SERVICES AND WITH OTHER PERSONS WITH WHOM YOU COMMUNICATE OR INTERACT AS A RESULT OF YOUR USE OF THE SITE, APPLICATION OR SERVICES, INCLUDING, BUT NOT LIMITED TO, RENTERS AND OWNERS, PARTICULARLY IF YOU DECIDE TO MEET OFFLINE OR IN PERSON REGARDLESS OF WHETHER SUCH MEETINGS ARE ORGANIZED BY The Capt App.</p>

            <p>YOU AUTHORIZE The Capt App, DIRECTLY OR THROUGH THIRD PARTIES, TO MAKE ANY INQUIRIES WE CONSIDER NECESSARY TO HELP VERIFY OR CHECK YOUR IDENTITY OR PREVENT FRAUD. THIS MAY INCLUDE ASKING YOU TO PROVIDE A FORM OF GOVERNMENT IDENTIFICATION (E.G. DRIVER’S LICENSE OR PASSPORT), YOUR DATE OF BIRTH, AND OTHER INFORMATION REQUIRING YOU TO TAKE STEPS TO CONFIRM OWNERSHIP OF YOUR EMAIL ADDRESS, PAYMENT METHODS OR PAYOUT METHODS; OR ATTEMPTING TO SCREEN YOUR INFORMATION AGAINST THIRD PARTY DATABASES. The Capt App RESERVES THE RIGHT TO CLOSE, SUSPEND, OR LIMIT ACCESS TO THE PAYMENT SERVICES IN THE EVENT WE ARE UNABLE TO OBTAIN OR VERIFY ANY OF THIS INFORMATION.</p>

            <p>NOTWITHSTANDING The Capt App’S APPOINTMENT AS THE LIMITED AGENT OF THE OWNERS FOR THE PURPOSE OF ACCEPTING PAYMENTS FROM RENTERS ON BEHALF OF THE OWNERS, The Capt App EXPLICITLY DISCLAIMS ALL LIABILITY FOR ANY ACT OR OMISSION OF ANY RENTER OR OTHER THIRD PARTY.</p>

            <p><strong>Limitation of Liability</strong></p>
            <p>YOU ACKNOWLEDGE AND AGREE THAT, TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE ENTIRE RISK ARISING OUT OF YOUR ACCESS TO AND USE OF THE SERVICES AND COLLECTIVE CONTENT, YOUR LISTING OR BOOKING OF AND USE OF ANY BOATS VIA THE SERVICES, , AND ANY CONTACT YOU HAVE WITH OTHER USERS OF THE SERVICES WHETHER IN PERSON OR ONLINE REMAINS WITH YOU. NEITHER The Capt App NOR ANY OTHER PARTY INVOLVED IN CREATING, PRODUCING, OR DELIVERING THE SERVICES, COLLECTIVE CONTENT WILL BE LIABLE FOR ANY INCIDENTAL, SPECIAL, PUNITIVE, EXEMPLARY OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, LOSS OF DATA OR LOSS OF GOODWILL, SERVICE INTERRUPTION, COMPUTER DAMAGE OR SYSTEM FAILURE OR THE COST OF SUBSTITUTE PRODUCTS OR SERVICES, OR FOR ANY DAMAGES FOR PERSONAL OR BODILY INJURY OR EMOTIONAL DISTRESS ARISING OUT OF OR IN CONNECTION WITH THESE TERMS, FROM THE USE OF OR INABILITY TO USE THE SERVICES OR COLLECTIVE CONTENT, FROM ANY COMMUNICATIONS, INTERACTIONS OR MEETINGS WITH OTHER USERS OF THE SERVICES OR OTHER PERSONS WITH WHOM YOU COMMUNICATE OR INTERACT AS A RESULT OF YOUR USE OF THE SERVICES, OR FROM YOUR LISTING, BOOKING, OR USE OF ANY BOAT VIA THE SERVICES, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR ANY OTHER LEGAL OR EQUITABLE THEORY, AND WHETHER OR NOT The Capt App HAS BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE, EVEN IF A LIMITED REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE.</p>

            <p>EXCEPT FOR OUR OBLIGATIONS TO PAY AMOUNTS TO APPLICABLE CAPTAINS PURSUANT TO THESE TERMS, IN NO EVENT WILL The Capt App'S AGGREGATE LIABILITY ARISING OUT OF OR IN CONNECTION WITH THESE TERMS AND YOUR USE OF THE SERVICES INCLUDING, BUT NOT LIMITED TO, FROM YOUR LISTING, BOOKING OR USE OF ANY BOAT VIA THE SERVICES, OR FROM THE USE OF OR INABILITY TO USE THE SERVICES, OR COLLECTIVE CONTENT AND IN CONNECTION WITH ANY BOAT OR INTERACTIONS WITH ANY OTHER MEMBERS, EXCEED THE AMOUNTS YOU HAVE PAID FOR BOOKINGS VIA THE SITE, APPLICATION AND SERVICES AS A GUEST IN THE TWELVE (12) MONTH PERIOD PRIOR TO THE EVENT GIVING RISE TO THE LIABILITY, OR IF YOU ARE AN OWNER, THE AMOUNTS PAID BY The Capt App TO YOU IN THE TWELVE (12) MONTH PERIOD PRIOR TO THE EVENT GIVING RISE TO THE LIABILITY, OR ONE HUNDRED DOLLARS ($100), IF NO SUCH PAYMENTS HAVE BEEN MADE, AS APPLICABLE. THE LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN The Capt App AND YOU. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, SO THE ABOVE LIMITATION MAY NOT APPLY TO YOU.</p>

            <p><strong>Indemnification</strong></p>
            <p>You agree to release, defend, indemnify, and hold The Capt App and its affiliates and subsidiaries, and their officers, directors, employees and agents, harmless from and against any claims, liabilities, damages, losses, and expenses, including, without limitation, reasonable legal and accounting fees, arising out of or in any way connected with (a) your access to or use of the Services or Collective Content or your violation of these Terms; (b) your Member Content; (c) your (i) interaction with any Member, (ii) booking or use of a Captain, (iii) creation of a Profile, including, but not limited to any injuries, losses, or damages (compensatory, direct, incidental, consequential or otherwise) of any kind arising in connection with or as a result of booking a Captain</p>

            <p><strong>Export Control and Restricted Countries</strong></p>
            <p>By using the Services, you represent and warrant that (i) neither you nor your listed Boat is located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a “terrorist supporting” country and (ii) you are not listed on any U.S. Government list of prohibited or restricted parties. You also will not use the Services for any purpose prohibited by U.S. law, including the development, design, manufacture or production of missiles, or nuclear, chemical or biological weapons. The Capt App does not permit Listings associated with certain countries due to U.S. embargo restrictions.</p>

            <p><strong>Reporting Misconduct</strong></p>
            <p>If you interact with another user of the Services who you feel is acting or has acted inappropriately, including but not limited to, anyone who (i) engages in offensive, violent or sexually inappropriate behavior, (ii) you suspect of stealing from you, or (iii) engages in any other disturbing conduct, you should immediately report such person to the appropriate authorities and then to The Capt App by contacting us with your police station and report number.</p>
            <p><strong>Entire Agreement</strong></p>
            <p>These Terms constitute the entire and exclusive understanding and agreement between The Capt App and you regarding the Services, Collective Content, and any bookings or Listings of Boats made via the Services, and these Terms supersede and replace any and all prior oral or written understandings or agreements between The Capt App and you regarding the foregoing.</p>
            <p><strong>Assignment</strong></p>
            <p>You may not assign or transfer these Terms, by operation of law or otherwise, without The Capt App's prior written consent. Any attempt by you to assign or transfer these Terms, without such consent, shall be void. The Capt App may assign or transfer these Terms, at its sole discretion, without restriction. Subject to the foregoing, these Terms will bind and inure to the benefit of the parties, their successors and permitted assigns.</p>

            <p><strong>Notices</strong></p>
            <p>Any notices or other communications permitted or required hereunder, including those regarding modifications to these Terms, will be in writing and given by The Capt App (i) via email (in each case to the address that you provide) or (ii) by posting to the Services. For notices made by e-mail, the date of receipt will be deemed the date on which such notice is transmitted.</p>
            <p><strong>Controlling Law and Jurisdiction</strong></p>
            <p>By using the Services, you agree that the Federal Arbitration Act, applicable federal law, and the laws of the State of New York, without regard to principles of conflict of laws, will govern these Terms and any dispute of any sort that might arise between you and The Capt App.</p>
            <p>You and we agree to submit to the personal jurisdiction of a state court located in Suffolk County, New York or a United States District Court, Southern District of New York located in New York, New York for any actions for which the parties seek injunctive or other equitable relief to prevent the actual or threatened infringement, misappropriation or violation of a party's copyrights, trademarks, trade secrets, patents, or other intellectual property rights, as set forth in the Dispute Resolution provision below.</p>
            <p><strong>Dispute Resolution</strong></p>
            <p>You and The Capt App agree that any dispute, claim or controversy arising out of or relating to these Terms or the breach, termination, enforcement, interpretation or validity thereof, or to the use of the Services (collectively, “Disputes”) will be settled by binding arbitration, except that each party retains the right to seek injunctive or other equitable relief in a court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation or violation of a party's copyrights, trademarks, trade secrets, patents, or other intellectual property rights. YOU ACKNOWLEDGE AND AGREE THAT YOU AND The Capt App ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS ACTION OR REPRESENTATIVE PROCEEDING. Further, unless both you and The Capt App otherwise agree in writing, the arbitrator may not consolidate more than one person's claims, and may not otherwise preside over any form of any class or representative proceeding. If this specific paragraph is held unenforceable, then the entirety of this “Dispute Resolution” section will be deemed void.</p> <p>Except as provided in the preceding sentence, this “Dispute Resolution” section will survive any termination of these Terms.
            Arbitration Rules and Governing Law. With the exception of claims under $15,000 in value, any arbitration will be administered by the American Arbitration Association (“AAA”) in accordance with the Commercial Arbitration Rules and the Supplementary Procedures for Consumer Related Disputes (the “AAA Rules”) then in effect, except as modified by this “Dispute Resolution" section. (The AAA Rules are available athttp://www.adr.org/arb_med or by calling the AAA at 1-800-778-7879.) The Federal Arbitration Act will govern the interpretation and enforcement of this section.</p>
            <p>You agree that any dispute, claim, or controversy under $15,000 in value arising out of or relating to these Terms, whether between you and The Capt App or between you and other users, or the existence, breach, termination, enforcement, interpretation, or validity thereof, shall be settled by binding arbitration administered by Fairclaims (www.FairClaims.com) and not in a court of law, in accordance with FairClaims’ procedures effective at the time a claim is made. You further agree that judgement on the award rendered by the arbitrator(s) may be entered in any court having jurisdiction thereof.</p>
            <p>Arbitration Process. A party who desires to initiate arbitration must provide the other party with a written Demand for Arbitration as specified in the AAA Rules. (The AAA provides a form Demand for Arbitration at http://www.adr.org/aaa/ShowPDF?doc=ADRSTG_004175 and a separate form for California residents athttp://adr.org/aaa/ShowPDF?doc=ADRSTG_004314.) The arbitrator will be either a retired judge or an attorney licensed to practice law in the state of California and will be selected by the parties from the AAA’s roster of consumer dispute arbitrators. If the parties are unable to agree upon an arbitrator within seven (7) days of delivery of the Demand for Arbitration, then the AAA will appoint the arbitrator in accordance with the AAA Rules.</p>
            <p>Arbitration Location and Procedure. Unless you and The Capt App otherwise agree, the arbitration will be conducted in Suffolk County, New York, USA. Subject to the AAA Rules, the arbitrator will have the discretion to direct a reasonable exchange of information by the parties, consistent with the expedited nature of the arbitration.</p>
            <p>Arbitrator’s Decision. The arbitrator will render an award within the time frame specified in the AAA Rules. The arbitrator's decision will include the essential findings and conclusions upon which the arbitrator based the award. Judgment on the arbitration award may be entered in any court having jurisdiction thereof. The arbitrator's award damages must be consistent with the terms of the “Limitation of Liability” section above as to the types and the amounts of damages for which a party may be held liable. The arbitrator may award declaratory or injunctive relief only in favor of the claimant and only to the extent necessary to provide relief warranted by the claimant's individual claim. If you prevail in arbitration you will be entitled to an award of attorneys' fees and expenses, to the extent provided under applicable law. The Capt App will not seek, and hereby waives all rights it may have under applicable law to recover, attorneys' fees and expenses if it prevails in arbitration.</p>
            <p>Fees. Your responsibility to pay any AAA filing, administrative and arbitrator fees will be solely as set forth in the AAA Rules.</p>
            <p>Claims.  YOU AGREE THAT ANY DISPUTES ARISING OUT OF OR RELATED TO THE SERVICES MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE DISPUTE ACCRUES.  OTHERWISE, THE DISPUTE IS PERMANENTLY BARRED.</p>
            <p>EU Residents.  If you are a consumer and have your habitual residence in the EU, you can elect to enjoy the protection afforded to you by mandatory provisions of the law of your country of residence.  You may bring a claim to enforce your consumer protection rights in connection with these Terms or in the EU country in which you live. The European Commission provides for an online dispute resolution platform, which you can access here: <a href="https://ec.europa.eu/consumers/odr">https://ec.europa.eu/consumers/odr</a>.</p>
            <p>Changes. Notwithstanding the provisions of the Modification section above, if The Capt App changes this Dispute Resolution section after the date you first accepted these Terms (or accepted any subsequent changes to these Terms), you may reject any such change by sending us written notice (within 30 days of the date such change became effective, as indicated in the Last Updated Date above or in the date of The Capt App’s email to you notifying you of such change. By rejecting any change, you are agreeing that you will arbitrate any Dispute between you and The Capt App in accordance with the provisions of this Dispute Resolution section as of the date you first accepted these Terms (or accepted any subsequent changes to these Terms).</p>
            <p><strong>General</strong></p>
            <p>The failure of The Capt App to enforce any right or provision of these Terms will not constitute a waiver of future enforcement of that right or provision. The waiver of any such right or provision will be effective only if in writing and signed by a duly authorized representative of The Capt App. Except as expressly set forth in these Terms, the exercise by either party of any of its remedies under these Terms will be without prejudice to its other remedies under these Terms or otherwise. If for any reason an arbitrator or a court of competent jurisdiction finds any provision of these Terms invalid or unenforceable, that provision will be enforced to the maximum extent permissible and the other provisions of these Terms will remain in full force and effect.</p>
            <p><strong>Contacting The Capt App</strong></p>
            <p>If you have any questions about these Terms of Service, please contact The Capt App Support <a href="mailto:contact@thecaptapp.com">contact@thecaptapp.com</a></p>
        </article>
    </section>
</template>

<script>
    export default {
        data() {
            return {
                URL: window.URL
            }
        },
        mounted() {            
        },

        created() {
        },
    }
</script>
